server:
  port: ${DATA_DOWNLOAD_SERVER_PORT:8080}
  servlet:
    context-path: /create-threat-model
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_NODES:localhost:5433}/${POSTGRESQL_DATABASE:the name of the database should be here}?loadBalanceHosts=true
    username: ${POSTGRESQL_USER:there should be a username here}
    password: ${POSTGRESQL_PASSWORD:there should be a password here}
parser:
  restltm: http://localhost:8080/threatmodel